### ISSUE TITLE
Release vs. Debug "Builds" and ASSERT+ENSURE

### ISSUE THREAD

**Issue by hostilefork** [rebol/rebol-issues#2252]
_(Note: I do not yet have access to tag this as being an "issue being raised" as opposed to bug, wish, etc.)_

The C culture of programming is distinct from the target audience for Rebol (despite the implementation). However, it's fairly well established in C that `assert(...)` is something that has no important side effects, and can be turned off in a release build.

So an issue is whether there should be a way to control if ASSERTs are run or not, or if there never will be such a switch.

If there is **not** a way, it should be articulated explicitly that there is no intention to support such features.  This way authors should not feel bad about putting code with important side-effects inside of an ASSERT... and for instance that they can depend on [ENSURE](https://github.com/metaeducation/ren-c/commit/051f2a9aaf13f11d5baba3e1810482c7b4a9240a) as a runtime check.

It should be mentioned that even in C and C++ there are people who believe that there should be no such thing as a "release" build and you should always "ship what you test".  So it's fairly reasonable to say that the built-in assert has no controls for disablement and never will--and users must create other constructs for checks that can be switched on/off.

There may be a way to compress this into the single line help string of the ASSERT function.

**Comment by ladislav** [comment]
I am using INCLUDE to define a directive of this kind. It simply vanishes from the production code when not needed.

**Comment by hostilefork** [comment]
This has been resolved in Ren-C with the creation of "noop dispatchers" and later HIJACKing.  So ASSERT is defined as a function with no body.  Its execution does not reify a frame, so it is very quick to execute.  It is only by injecting behavior via HIJACK which has the processing.

There is a separation of VERIFY and ASSERT, where VERIFY is the version that is a native that will always run with the program.
