### ISSUE TITLE
Behavior of DOES w.r.t. locals and RETURN

### ISSUE THREAD

**Issue by hostilefork** [rebol/rebol-issues#2265]
Red, R3-Alpha, and Ren-C all believe that the value of auto-gathering "locals" by default is high, so the FUNCTION abstraction does this...where FUNC is reserved for users who want explicit control over the locals additively (e.g. without having to mention which set-words in the body specifically to omit.)

But in R3-Alpha and Red, **does [...]** behaves as **func [] [...]** and not **function [] [...]**.  When it has been proposed that perhaps DOES should match FUNCTION, the question has come up what to call the non-gathering analogue.  Since **do** has other meanings, this means the only "drop letters" way to make a parallel would be **doe/does**.  While the func/function distinction is "ugly but kind of learnable and comprehensible", **doe** is completely intolerable.

So one axis of thinking was that perhaps FUNCTION would have a refinement (e.g. /ONLY, or some other more meaningful name) instructing it to not gather arguments.  Then make DOES gather by default, but offer the same refinement.  _(Note: The /ONLY refinement does not mean FUNCTION/ONLY would be a synonym for FUNC...just that it wouldn't gather.  R3-Alpha already had features of FUNCTION that are not present in FUNC, and in Ren-C the distinction of their feature sets is foundational to how it can efficiently implement definitional returns without "baking in" RETURN as a keyword somehow.)_

Relegating the non-gathered form to the "more esoteric" does/only has the nice property that a new user who isn't yet aware of the FUNC and FUNCTION distinction can just think of **does [...]** as just being **function [] [...]**.

HOWEVER existing usages of **does** are used _mostly_ inside of other functions to define a reusable unit of work.  To make a contrived example:

```
  gather-groups-of-5: function [block] [
      current: copy []
      gathered: copy []
      accumulate: does [
          either length current = 5 [
              append/only gathered current 
              current: copy [] ;-- start new group
          ][
              append current number
          ]
      ]
      number: none
      for-each item block [
          number: item
          accumulate
      ]
 ]
```

While this one is made up, there are things "like it" which expect to have write access to locals in the enclosing environment.

Despite this there are several reasons to favor the concept that DOES acts like FUNCTION without a spec, as opposed to FUNC without a spec, and gathers by default.  Ren-C makes it more likely that a mistake regarding assumptions that locals are not gathered would be noticed because locals and refinement arguments are unset by default, and not none...so accesses prior to assignment would cause errors.  **func [] [...]** is not that hard to write for those who want it, and DOES/ONLY could be supplied.

One particularly deep reason for wanting this coming from Ren-C is that objects have specs, and are constructed e.g. as **obj: construct [x get-y] [x: 10 | y: 20 | get-y: does [return y]]**.  This would mean that **y** would be auto-gathered as a private member of obj (similar to a local).  By contrast, **y: 0 | obj: construct/only [x get-y] [x: 10 | y: 20 | get-y: does [return y]]** would be working with whatever binding y already had...here likely assigning and fetching the outer y.

Yet there is still a single-arity variant of construct... the parallel to DOES for FUNCTION.  It is called HAS _(and aliased to OBJECT in r3-legacy, where HAS is then also aliased to its rarely-used meaning for declaring functions with local variables but no arguments)_.  However, to be of general use for an object, HAS _must_ auto-gather...since objects with no fields aren't much use.  So the big picture of consistency suggests the necessity of DOES gathering by default.

_(Note: Making objects that don't gather is not necessarily useless, *if_ that object has a SELF defined...and if it permits dynamic additions of fields by runtime code.  So **x: 0 | foo: has/only [x: x + 10 | append self [y: x]]**, for instance, could be useful for creating objects whose entire content was coming from dynamic code and did not want to be burdened by either a gathering process -or- a spec.)*

**Comment by hostilefork** [comment]
In looking at this more, I feel that treating **does [...]** as a way of writing either **FUNCTION [] [...]** or **FUNC [] [...]** isn't particularly productive.  How lazy are people, after all?  :-)

The more interesting application is almost certainly as a factoring tool inside of functions, where code inside the DOES is transparent to its surroundings.  But to get that transparency, it actually suggests that *DOES shouldn't have its own definitional return*.  This would let you author repeated portions, with read and write access to that function's variables...and even to use RETURN from the enclosing function.  In Ren-C, that lack of response to return is accomplished with **does: func [body] [make function! reduce [[] body]**.

*(With [UNWIND](https://trello.com/c/noiletwM/111-unwind-can-dynamically-trigger-a-return-from-any-running-frame) you could still "return from a DOES" if you had its function, e.g. `bar: does [unwind/with :bar <return-value> print "this wouldn't print"]`...though it would likely be clearer to use THROW and CATCH.)*

It isn't so bad to lose a name for the zero-arity version of FUNCTION or FUNC.  They might not need names anyway.  Skipping out on the function spec means no description, and even with no arguments there's no documentation of the `return:` type (in Ren-C).  So those attracted to the "elegance" of a single-word definition for DOES, enough to try using it for top-level functions, might be argued to have misplaced priorities.

**Comment by IngoHohmann** [comment]
+1 I never liked has/does for functions, partly because of the reasons given.
