### ISSUE TITLE
Make PARSE's IF an arity-2 operation, instead of arity-1

### ISSUE THREAD

**Issue by hostilefork** [rebol/rebol-issues#2271]
The current implementation of IF considers it to be a standalone, arity-1 operation, which either allows you to keep processing or fail:

    >> parse "" [if (true)]
    == true

    >> parse "" [if (false)]
    == false

This is quite counter-intuitive, and as a pattern is not extensible to allow for things like EITHER.  It would line up better with the expectations of users and the behaviors of the language in general if it were arity-2, as most would expect...and if it failed, it simply did not contribute the corresponding rule.

     >> parse "ac" ["a" if (false) ["b"] "c"]
     true

     >> parse "abc" ["a" if (true) ["b"] "c"]
     true

If coupled with an EITHER construct, then this could use a single condition to trigger failure or not, e.g.

    >> parse "abc" ["a" either (condition) ["b"] [reject] "c"]

**Comment by hostilefork** [comment]
Note this Red user faced the exact same confusion: https://gitter.im/red/red/welcome?at=59080fc808c00c092ad567aa

**Comment by IngoHohmann** [comment]
I like the arity-2 version a lot better.

**Comment by hostilefork** [comment]
Ren-C has rethought how PARSE interacts with conditionals to say that LOGIC! #[true] means "keep parsing", and LOGIC! #[false] means "fail this rule".  NULL also means "keep parsing".

This means the FAIL keyword is now just FALSE.  (Which is good, as FAIL has a harsher connotation in terms of raising errors.)

But it also means that PARSE does not need to re-create the entire conditional logic from the main language.  It doesn't need an EITHER or SWITCH or CASE, etc.  It just needs a way to splice results of a GROUP! execution into code.

     >> did parse "ac" ["a" :(if false '["b"]) "c"]
     == #[true]

     >> did parse "abc" ["a" :(if true '["b"]) "c"]
     == #[true]

The current main issue of contention is whether the **:(...)** is a good idea or not.  An earlier concept used **((...))** before that was taken to mean "splice" by COMPOSE.

@rgchris dislikes symbols and has suggested that perhaps even breaking with tradition and saying plain GROUP! always puts its result into the stream of the parse rules would be better.  Then relying on an ELIDE keyword if you wanted to run code but not have a side effect (or have your expression end in NULL).  It would be a significant incompatibility, but perhaps it is the more natural way of thinking about it.

**Upshot being: the IF construct...and FAIL...are deprecated in Ren-C.**
