### ISSUE TITLE
PROTECT-ed series are not protected against REMOVE-EACH

### ISSUE THREAD

**Issue by hostilefork** [rebol/rebol-issues#2272]
>> block: [1 2 3] 
    == [1 2 3]

    >> protect block
    == [1 2 3]

    >> remove-each item x [item = 1]
    == 1

    >> x
    [2 3]

Issue originally raised by @rgchris for Ren-C, which has more automatic locking and protection, making the bug more obvious.

https://github.com/metaeducation/ren-c/issues/612

**Comment by Oldes** [comment]
This issue is duplicate of: https://github.com/rebol/rebol-issues/issues/1780
