### ISSUE TITLE
Decide meaning for lone # symbol

### ISSUE THREAD

**Issue by hostilefork** [rebol/rebol-issues#2297]
Rebol2 made # an empty ISSUE!:

    rebol2> type? #
    == issue!

    rebol2> length? #
    == 0

When its category was changed from ANY-STRING! to ANY-WORD!, empty words were not legal *(as empty strings were)*.  Red addressed this by making them illegal:

    red> #
    *** Syntax Error: invalid issue! at "#"

Though a little-known change in R3-Alpha made # a shorthand for NONE!:

    >> #
    == none

Given that # is already quite overloaded in the language, this seems an odd choice.  No one has reported using it, and people seem to generally dislike it.  Another application--or raising an error like Red--should likely be chosen.

---

The following are from the test suite for Rebol2's issue tests:

    [issue? #]
    [# == #[issue! ""]]
    [# == make issue! 0]
    [# == to issue! ""]

**Comment by iArnold** [comment]
Change the Synyonym ;-)

**Comment by hostilefork** [comment]
Ren-C moved to making it an error:

https://github.com/metaeducation/ren-c/commit/f3002b1458e08ff24eeac12e96c2331ab1118159

...but hasn't yet determined its fate more generally.

One desirable aspect of an outcome for what `#` should be is that whatever it is loaded as, *the TO STRING! of it* (to text! in Ren-C) should be "#".  See this forum post for some of the motivation of why one would want that:

https://forum.rebol.info/t/discovering-words-as-any-string/695

If it were an empty ISSUE!, that seems it would work out for that part of the rule.

**Comment by hostilefork** [comment]
ISSUE! and CHAR! were unified into a single type (name of combined type TBD, still called ISSUE! for the moment).

Type constraints let you type check single-character issues as **`[char?]`**.

The seemingly sensible choice here is to make **#** be a representation for ASCII 0, e.g. a NUL character ('\0' in C).

ANY-STRING! values in Ren-C cannot have any zero codepoints inside them.

    >> insert "abcdef" #
    ** Script Error: #{00} bytes illegal in ANY-STRING?, use BINARY!

But BINARY! allows it:

    >> append #{DECAFBAD} #
    == #{DECAFBAD00}

You can use the # in dialects for whatever purpose.  They are truthy and not accepted most places.

> Though a little-known change in R3-Alpha made # a shorthand for NONE!:
>
>     >> #
>     == none

Ren-C has a diverse set of single-character offerings.  BLANK! (_) and TRASH (~) are available as substitutes for what NONE! was for in reified contexts like blocks.

However, anything you can put in a BLOCK! is truthy.
