### ISSUE TITLE
Path-picking characters out of FILE! with INTEGER! does not work

### ISSUE THREAD

**Issue by hostilefork** [rebol/rebol-issues#2305]
Picking a character out of a STRING!, it works as with other series types.  You can do this with either PICK or a PATH!.  So for **string: "foo"**

    >> pick string 1
    == #"f"

    >> string/1
    == #"f"

Though in the ANY-STRING! typeclass, FILE! is different.  So with **file: %foo**

    >> pick file 1
    == #"f"

    >> file/1
    == %foo/1

PATH!-ing has been overloaded for the general function that "pathing out of a FILE! or URL! will create a compound path".  The behavior is somewhat nuanced, with slashes merged.  So with **slashed: %bar/** and **unslashed: %bar**

    >> slashed/(file)
    == %bar/foo

    >> unslashed/(file)
     == %bar/foo

While this behavior has its uses, competing with the behavior of picking integers doing indexed access is fairly fundamental...suggesting this should be done somewhere else.  One possibility would be if you were to [MAKE FILE! out of a PATH!](https://forum.rebol.info/t/newerpath-making-a-generic-pathing-operator/422/7).

**Comment by Oldes** [comment]
I prefer:
```
dir/subdir/(rejoin ["file-" num ".txt"])
```
instead of:
```
make file! '(dir)/subdir/["file-" num ".txt"]
```
I have no idea why I should use `dir/1` pick up (and if I needed it, I can still use `pick dir 1`)
So for me it is not an issue.

**Comment by hostilefork** [comment]
Solved with elegance by the %% operator.

https://forum.rebol.info/t/make-file-and-unleashed-time-to-use-it/1398
