### ISSUE TITLE
PORT! state binary appears empty when it is not

### ISSUE THREAD

**Issue by hostilefork** [rebol/rebol-issues#2314]
The port state in the following examples contains bytes that are being used by the port, yet appear empty--meaning the bytes won't be copied, and it breaks the invariant of a BINARY! which may trip up in other ways:

    >> p: open %test.txt
    >> p/state
    == #{}

    >> p: open http://example.com
    >> open p
    >> p/state/connection/state
    == #{}

The reason this happens is that the binary is created, but the length is never set:

https://github.com/rebol/rebol/blob/25033f897b2bd466068d7663563cd3ff64740b94/src/core/c-port.c#L100

[Make_Binary()](https://github.com/rebol/rebol/blob/25033f897b2bd466068d7663563cd3ff64740b94/src/core/s-make.c#L43) takes a *capacity*, but [Make_Series()](https://github.com/rebol/rebol/blob/25033f897b2bd466068d7663563cd3ff64740b94/src/core/m-pools.c#L422) sets the length to 0, regardless of that capacity.

**Comment by hostilefork** [comment]
This was resolved in Ren-C some time ago, just mentioning it because it came up trying to write up some history-of-ports-in-R3-Alpha document, and it's easier to point to this issue than to go on a tangent about it in that document.

**Comment by Oldes** [comment]
@hostilefork in such a cases it would be helpful to see commit which contain the fix.

**Comment by Oldes** [comment]
Question is.. if this value should be accessible.. when it is internal private area.

**Comment by hostilefork** [comment]
> Question is.. if this value should be accessible.. when it is internal private area.

If you want more opacity, the HANDLE! type was introduced for that.  But I'm more interested in turning this binary-representation-of-a-C-struct into a Rebol-structured OBJECT!, for more transparency.

My point about the binary is just that if the length is incorrect, then operations like copying and such won't work...the copy will be empty though the original was not.  And of course it confuses people who are working on the "internal implementation" who wonder "huh, I didn't think it was empty, why is it empty?"  Or perhaps someone upgrades the GC to reclaim space and it says "oh, the allocation here is bigger than the length, we can shorten that".

**Comment by Oldes** [comment]
The question is, why [this line](https://github.com/rebol/rebol/blob/25033f897b2bd466068d7663563cd3ff64740b94/src/core/c-port.c#L105) was commented out.

**Comment by Oldes** [comment]
And yes... Ren-C is hardly mappable back because you rename almost everything in your code.

**Comment by Oldes** [comment]
When someone else will be reading it... the `Guard_Series` call in the original code was removed by Atronix in this commit: https://github.com/zsx/r3/commit/4d7e52114db6537a76aaa3efa7060a8e296c391a

**Comment by Oldes** [comment]
In my branch it is now:
```
>> p: open %sss  
>> p/state      
== #{
000000000300000000000000000000003060AD0A010000000500000000000000
0200000000000000030100001100000000000000000000000000000000000000
0000000030198E8BC17F00000000000000000000000000000000000090D9245B
00000000
}

>> clear p/state 
** Script error: protected value or series - cannot modify
** Where: clear
** Near: clear p/state
```

Let's see if it breaks something.
