### ISSUE TITLE
Zero to the power of zero is 1 instead of 0

### ISSUE THREAD

**Issue by Oldes** [rebol/rebol-issues#2315]
So far in Rebol `power 0 0` was returning `0.0`, in Red it is `1` and it looks it is the generally agreed upon answer.

Here is some math explanation: https://medium.com/i-math/the-zero-power-rule-explained-449b4bd6934d

**Comment by Oldes** [comment]
With the above commit:
```
>> power 0 0
== 1.0
```

**Comment by hostilefork** [comment]
I'd probably have leaned to raising an error myself, but it does seem the general consensus of the programming community is it's more useful as 1, and even Don Knuth recommends it:

https://rosettacode.org/wiki/Zero_to_the_zero_power

Changed Ren-C to match.

https://github.com/metaeducation/ren-c/commit/8f90abe114b278c98bc1e07b387e8cc1269bb130
