### ISSUE TITLE
DELINE / ENLINE does not check series' protection

### ISSUE THREAD

**Issue by Oldes** [rebol/rebol-issues#2325]
Now:
```
>> x: protect "ab^M^/c"
== "ab^M^/c"

>> clear x
** Script error: protected value or series - cannot modify
** Where: clear
** Near: clear x

>> deline x
== "ab^/c" ;<----- should be error too!

>> x
== "ab^/c" ;<------ series was modified even when it is protected
```

**Comment by hostilefork** [comment]
Systemically solved by `const REBSER*` vs. `REBSER*` access.  Any such error would be caught at compile-time.

https://forum.rebol.info/t/source-mutability-const-and-mutable/976/5

**Comment by Oldes** [comment]
It is possible to set protection on runtime which cannot be catched by any C++ trick, imho.

**Comment by hostilefork** [comment]
No clue what that sentence is supposed to mean, and I don't have to care.
