### ISSUE TITLE
array only works with the /initial refinement

### ISSUE THREAD

**Issue by OneArb** [rebol/rebol-issues#2368]
`array [ 5 ] `
** Script Error: insert does not allow blank! for its series argument
** Where: else array console
** Near: [... try get 'value ~~ size]

`array  5`
** Script Error: insert does not allow blank! for its series argument
** Where: else array console
** Near: [... try get 'value ~~ size]

**Comment by hostilefork** [comment]
*(Note: I've always disliked the name of ARRAY.  :-/  Too noun-ish to be used as a verb.)*

Seemed there'd never been any tests for it, I added a few, and fixed the problem:

https://github.com/metaeducation/ren-c/commit/3ff2944d0ef9182ec0bfb335b092202e5e2a8a90

It actually gave some insights to the "refinement-is-the-argument" plan, which I am now very keen on:

https://forum.rebol.info/t/pure-and-refined-simplifying-refinements-to-one-or-zero-args/1120/4

**Comment by hostilefork** [comment]
@OneArb Note: The `rebol-issues` repository is currently for issues that occur in R3-Alpha, e.g. the downloads here:

http://rebolsource.net/

Issues that are Ren-C only are tracked in:

https://github.com/metaeducation/ren-c/issues

So when looking at an issue, please check to see which is most applicable.  If the problem exists in both, then in that case you should post about it here.

(While I may think issues should converge at some point, it is actually helpful for the time being to know whether something is an "old" issue or a "new" one.)
