### ISSUE TITLE
DECODE-URL does not support UNICODE

### ISSUE THREAD

**Issue by Oldes** [rebol/rebol-issues#2380]
`decode-url` implementation was not done with Unicode support.
Notice the truncated `path` value bellow:
```
>> decode-url http://httpbin.org/get?q=ščřž
== [scheme: 'http host: "httpbin.org" path: "/get?q="]
```

Related issues: https://github.com/rebol/rebol-issues/issues/482, https://github.com/rebol/rebol-issues/issues/2379 and https://github.com/rebol/rebol-issues/issues/2013

**Comment by hostilefork** [comment]
Assuming Oldes fix is better than what was there--seems to work.  Incorporating it just to get the issue closed...

https://github.com/metaeducation/ren-c/commit/d89efe2a9e52aada28abff343af7d679359eec10
