### ISSUE TITLE
Comparing two pair! could be allowed

### ISSUE THREAD

**Issue by Oldes** [rebol/rebol-issues#2391]
Although there is [compare code in the original source base](https://github.com/rebol/rebol/blob/25033f897b2bd466068d7663563cd3ff64740b94/src/core/t-pair.c#L83-L96), comparing two pairs now throws an error:
```
>> 1x1 < 2x2
** Script error: cannot compare pair! with pair!
** Where: <
** Near: < 2x2
```
Expected result is like in Red:
```
>> 1x1 < 2x2
== true
>>
```

**Comment by Oldes** [comment]
hm.. the code is there for sorting purposes, and with direct comparison like mentioned above is hard to find result, which would be useful in all use cases. That is probably reason, why it was never allowed.

**Comment by Oldes** [comment]
It would be good to note here, that current Red sorting precedence is:
```
>> sort [1x2 1x1 2x1 2x2]
== [1x1 1x2 2x1 2x2]
```
while in Rebol it is/was:
```
>> sort [1x2 1x1 2x1 2x2]
== [1x1 2x1 1x2 2x2]
```

**Comment by Mark-hi** [comment]
I would like to see the norm be used, so 1x2 would compare equal to 2x1, and 7x7 less than both of 1x50 and 50x1.

**Comment by Oldes** [comment]
@Mark-hi having `1x1 = 2x1` would break pretty everything, that is a no go. I will probably keep current state, although while working with images quite a lot these days, I'm always in a temptation to use something like `position < image-size` to find, if I'm out of bounds. Rebol2 and Red has `WITHIN?` function for it, but I'm not sure if the required `offset` is good thing, because in my case it would look like:
```
if within? position 0x0 image-size [...]
```
which I don't consider to be nice to read.

**Comment by Mark-hi** [comment]
Did you mean 1x2 = 2x1 would break everything?
Because 1x1 < 2x1 in my proposal, so I otherwise don't know what you mean.

**Comment by Mark-hi** [comment]
Your idea of "position within image" is kind of cool actually, but it would break totality; 1x2 would be none of equal, greater, or less than 2x1.

**Comment by Oldes** [comment]
I'm keeping it as it is... with the strange error.. for now.
