### ISSUE TITLE
test: copy/part tail [1] -1 fails on arm

### ISSUE THREAD

**Issue by IngoHohmann** [rebol/rebol-issues#2486]
```
>> copy/part tail [1] -1
== []

>> copy/part tail [1] -2147483647
== []

>> copy/part tail [1] -2147483648
== []
```

(should have been [1] in all 3 cases)

**Comment by hostilefork** [comment]
Thanks...well, that's bizarre, I guess I'll have to look and see by inspection why ARM would be different.  It may point to a broader issue, we'll see...
