### ISSUE TITLE
`equal?` with maps causes assertion

### ISSUE THREAD

**Issue by giuliolunati** [rebol/rebol-issues#2498]
`(make map! []) = (make map! [])`

causes

`../src/include/sys-array.h:286: VAL_ARRAY: assertion "ANY_ARRAY(v)" failed`

**Comment by hostilefork** [comment]
This is an R3-Alpha bug that Ren-C's asserts uncovered, so moving the issue there...

https://github.com/rebol/rebol-issues/issues/2340
