### ISSUE TITLE
Can't CUSTOMize /

### ISSUE THREAD

**Issue by giuliolunati** [rebol/rebol-issues#2516]
My CUSTOM module let me write e.g.
`(2 / 3) + (1 / 2) = (7 / 6)`
and 
`(1 +i 1) / (1 -i 1) = i`

That worked when / was a WORD, but now it's a PATH and I can't find no way to work around.

**Comment by hostilefork** [comment]
As described in chat, [here is a very experimental solution](https://github.com/metaeducation/ren-c/commit/b7dd04d0b5238b133ca087b58ec84e6d757fe5b6) of binding `/` as `-slash-1-`.  If it seems to generally work out, then it can be made more rigorous...and add the other `-slash-N-` values for things like `//` and so on.

    code: [1 / 2]
    obj: make object! [
        -slash-1-: enfix func [a b] [
            return reduce '(b a)
        ]
    ]
    0.5 = do code
    bind code obj
    '(2 1) = do code

It uses some very weird untested properties, so there might be strange bugs.  Run debug builds whenever possible.

Adding more tests would be ideal!!

**Comment by giuliolunati** [comment]
Many thanks for your care! I run to test it!

**Comment by giuliolunati** [comment]
It works!
